name: Test Node Application
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v6
            - name: Installing Node 
              uses: actions/setup-node@v6
              with :
                node-version: latest
            - name: Test the Application 
              run: npm test




